name: menutri_app
description: "Menutri - Discover healthy food and restaurants"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.0
  firebase_analytics: ^11.3.0
  material_symbols_icons: ^4.2719.0
  drag_and_drop_lists: ^0.4.1
  flutter_localizations:
    sdk: flutter

  # Sentry error & performance monitoring
  sentry_flutter: ^8.7.0

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^16.2.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # State Management
  flutter_riverpod: ^2.5.1

  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2

  # Camera & Scanning
  camera: ^0.11.0+2
  mobile_scanner: ^7.0.1

  # Location & Maps
  geolocator: ^14.0.2
  google_maps_flutter: ^2.9.0

  # Sharing & External
  share_plus: ^11.1.0
  url_launcher: ^6.3.0

  # Data & CSV
  csv: ^6.0.0
  intl: ^0.20.2

  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
